name: flutter_timer
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  time_split_api:
    path: packages/time_split_api/
  local_time_split_api:
    path: packages/local_time_split_api/
  time_split_repository:
    path: packages/time_split_repository/

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
  build_runner: ^2.3.3
  mockingjay: ^0.3.0

flutter:
  uses-material-design: true
