name: local_time_split_api
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0-233.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  rxdart: ^0.27.5
  time_split_api:
    path: ../time_split_api/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
